"""Historical dashboard mart contracts."""

from retail_analytics.mart.builds import (
    MartBuildMetadata,
    MartBuildStatus,
    mart_build_id,
    mart_build_metadata_from_frame,
    mart_build_metadata_to_frame,
    read_mart_build_metadata,
    write_mart_build_metadata,
    write_mart_build_metadata_dataset,
)
from retail_analytics.mart.comparison_universe import (
    ComparativePatternSignal,
    DeclineSpeedResult,
    DeltaStatus,
    MarketSegmentDelta,
    MarketSegmentUniverse,
    calculate_decline_speed_ratio,
    calculate_market_segment_delta,
    filter_market_universe,
    private_label_growth_while_portfolio_declines,
)
from retail_analytics.mart.duckdb import query_metric_facts
from retail_analytics.mart.geography import (
    UNKNOWN_REGION,
    RegionalMetricRow,
    calculate_regional_summary,
)
from retail_analytics.mart.metric_catalog import (
    CatalogIssueSeverity,
    CatalogValidationIssue,
    DashboardGroup,
    EffectiveMetricCatalogEntry,
    MetricAvailabilityStatus,
    MetricFormat,
    PrivateMetricCatalogOverride,
    PublicMetricCatalogEntry,
    catalog_entry_for_fact,
    load_private_metric_catalog_overrides,
    load_public_metric_catalog,
    merge_metric_catalog,
    validate_metric_catalog,
)
from retail_analytics.mart.metric_facts import (
    RangeAggregationStrategy,
    build_mart_metric_facts,
    duplicate_semantic_identities,
    metric_fact_semantic_identity_columns,
    range_strategy_for_metric,
    read_mart_metric_facts,
    write_mart_metric_fact_dataset,
    write_mart_metric_facts,
)
from retail_analytics.mart.portfolio import (
    ActiveSkuSummary,
    BrandVsCategoryComparison,
    CategoryShareResult,
    ShareMetric,
    calculate_active_sku_summary,
    calculate_category_share,
    compare_brand_to_category,
)
from retail_analytics.mart.query import (
    ComparisonMode,
    ComparisonResult,
    CoverageStatus,
    DashboardMartQueryService,
    DashboardMetricQueryRequest,
    DashboardMetricQueryResponse,
    MetricDefinitionLineage,
    MetricQueryResult,
    PeriodMode,
    PeriodValue,
    QualityPolicy,
    QueryLimitation,
)
from retail_analytics.mart.rankings import ManufacturerRankRow, RankingScope, rank_manufacturers
from retail_analytics.mart.scoped_metrics import (
    ScopedMetricsResult,
    calculate_private_label_scope_set,
    calculate_private_label_scoped_metrics,
)
from retail_analytics.mart.scopes import (
    PrivateLabelScope,
    PrivateLabelScopeResult,
    apply_private_label_scope,
    scope_identity_hash,
)

__all__ = [
    "UNKNOWN_REGION",
    "ActiveSkuSummary",
    "BrandVsCategoryComparison",
    "CatalogIssueSeverity",
    "CatalogValidationIssue",
    "CategoryShareResult",
    "ComparativePatternSignal",
    "ComparisonMode",
    "ComparisonResult",
    "CoverageStatus",
    "DashboardGroup",
    "DashboardMartQueryService",
    "DashboardMetricQueryRequest",
    "DashboardMetricQueryResponse",
    "DeclineSpeedResult",
    "DeltaStatus",
    "EffectiveMetricCatalogEntry",
    "ManufacturerRankRow",
    "MarketSegmentDelta",
    "MarketSegmentUniverse",
    "MartBuildMetadata",
    "MartBuildStatus",
    "MetricAvailabilityStatus",
    "MetricDefinitionLineage",
    "MetricFormat",
    "MetricQueryResult",
    "PeriodMode",
    "PeriodValue",
    "PrivateLabelScope",
    "PrivateLabelScopeResult",
    "PrivateMetricCatalogOverride",
    "PublicMetricCatalogEntry",
    "QualityPolicy",
    "QueryLimitation",
    "RangeAggregationStrategy",
    "RankingScope",
    "RegionalMetricRow",
    "ScopedMetricsResult",
    "ShareMetric",
    "apply_private_label_scope",
    "build_mart_metric_facts",
    "calculate_active_sku_summary",
    "calculate_category_share",
    "calculate_decline_speed_ratio",
    "calculate_market_segment_delta",
    "calculate_private_label_scope_set",
    "calculate_private_label_scoped_metrics",
    "calculate_regional_summary",
    "catalog_entry_for_fact",
    "compare_brand_to_category",
    "duplicate_semantic_identities",
    "filter_market_universe",
    "load_private_metric_catalog_overrides",
    "load_public_metric_catalog",
    "mart_build_id",
    "mart_build_metadata_from_frame",
    "mart_build_metadata_to_frame",
    "merge_metric_catalog",
    "metric_fact_semantic_identity_columns",
    "private_label_growth_while_portfolio_declines",
    "query_metric_facts",
    "range_strategy_for_metric",
    "rank_manufacturers",
    "read_mart_build_metadata",
    "read_mart_metric_facts",
    "scope_identity_hash",
    "validate_metric_catalog",
    "write_mart_build_metadata",
    "write_mart_build_metadata_dataset",
    "write_mart_metric_fact_dataset",
    "write_mart_metric_facts",
]

